spring:
  mail:
    host: smtp.163.com
    username: 13607563956@163.com
    password: VRfyW4t8UvYLeGZ8
  rabbitmq:
#    addresses: 10.211.55.4
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
  security:
    filter:
      order: -100
    jwt:
      key: abcekadfdl
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
  weather:
    key: d7428a1b805f4e8e9fe9806cb3f39fbe
    apiHost: me487qq4gv.re.qweatherapi.com
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minio'
    password: 'password'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  ai:
    deepseek:
      api-key: sk-0ca2801a634d470bbad1f14276ba9e3d